# Generated by Django 3.2.25 on 2024-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_purchases',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
