# Generated by Django 3.2.25 on 2024-09-10 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
