# Generated by Django 3.2.25 on 2024-09-10 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_productreview_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
