# Generated by Django 3.2.25 on 2024-09-16 13:52
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_productreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
