# Generated by Django 3.2.25 on 2024-08-31 13:13
# flake8: noqa
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='colours',
            options={'verbose_name_plural': 'Colours'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name_plural': 'Profession'},
        ),
    ]
