# Generated by Django 3.2.25 on 2024-09-02 09:23
# flake8: noqa
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240831_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
